general.import = ["~/.config/alacritty/one_light.toml"]


[font]
size = 7.0
[font.normal]
family = "Sarasa Mono TC Nerd"

[cursor]
[cursor.style]
# shape = "Beam"

[window]
# decorations = "None"
# opacity = 0.7

