general.import = ["~/.config/alacritty/one_light.toml"]


[font]
size = 10.0
[font.normal]
family = "JetBrains Mono Nerd Font"

[cursor]
[cursor.style]
# shape = "Beam"

[window]
# decorations = "None"
# opacity = 0.7

